Add bookings
DaniilRyndyk1/java-shareit pull request #2
Opened 2023-07-28 20:30 UTC by DaniilRyndyk1

2023-07-31 08:32 UTC, Fleaman777 requested changes

2023-07-31 08:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final String userHeaderName = "X-Sharer-User-Id";
userHeaderName - больше похоже на константу, 
можно сделать статичной переменной

2023-07-31 08:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +@Repository
в данном случае можно не использовать эту аннотацию, т.к по сути JpaRepository ее содержит

2023-07-31 08:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    private void validateBooking(Booking booking) {
private методы должны идти после публичных, так при беглом просмотре класса, можно будет быстро понять, какой функционал он отдает наружу

2023-07-31 08:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        }
такую проверку можно было бы вынести  в отдельный вспомогательный метод

2023-07-31 08:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +            throw new NotFoundException("Бронирование с таким id не существует");
у Optional класса есть хороший метод orElseThrow 
отлично сюда впишется и сократит количество кода

2023-07-31 08:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
Если будет время, рекомендую почитать:
https://habr.com/ru/companies/haulmont/articles/564682/
Это о том, почему @Data и JPA лучше вместе не использовать

2023-07-31 08:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        }
аналогично, 

общую логику можно вынести в отдельный приватный метод

2023-07-31 08:32 UTC, Fleaman777 commented on src/main/resources/application.properties
> +#spring.datasource.driver-class-name=org.postgresql.Driver
в этом приложении, согласно заданию, должен использоваться постргрес драйвер

2023-08-01 19:19 UTC, DaniilRyndyk1 commented on src/main/resources/application.properties
> +#spring.datasource.driver-class-name=org.postgresql.Driver
я тоже так думал, но в пачке сказали использовать h2 для гитхаб тестов.[https://disk.yandex.ru/i/7G4xVzPX3iPeBw](url)

2023-08-02 18:57 UTC, TyutterinYakov reviewed
Добрый вечер! В целом - хорошо) Отметил то, что следует исправить и то, что можно сделать лучше - "(предложение)". Хорошего вечера! Если возникнут вопросы по ревью - пиши в пачку, буду рад помочь🌃

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public BookingDto toDto() {
Подобную логику принято располагать в отдельных классах-мапперах, а не внутри классов-моделей)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    public BookingInfoDto toInfo() {
Подобную логику принято располагать в отдельных классах-мапперах, а не внутри классов-дто)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
Классы-DTO не должны содержать в себе сложные объекты по типу классов-сущностей. Мы всегда должны контролировать те данные, что получаем и отдаем. Не только в целях безопасности, но и производительности, так как зачем тратить ресурсы на передачу тех данных, что не будут использоваться
Можно было бы представить их в виде внутренних публичных и статических, так как они будут связаны лишь с текущим классов-DTO)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private User booker;
Классы-DTO не должны содержать в себе сложные объекты по типу классов-сущностей. Мы всегда должны контролировать те данные, что получаем и отдаем. Не только в целях безопасности, но и производительности, так как зачем тратить ресурсы на передачу тех данных, что не будут использоваться
Можно было бы представить их в виде внутренних публичных и статических, так как они будут связаны лишь с текущим классов-DTO)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInputDto.java
> +    public Booking toBooking(User user, Item item) {
Аналогично, должен находиться в классе-маппере)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInputDto.java
> +public class BookingInputDto {
Так же хорошо было бы использовать более декларативный подход и навесить над полями start и end соответствующие аннотации валидации)
Например, над start - `@FutureOrPresent`, так как дата начала бронирования может быть равна текущей, либо же быть из будущего. Не забываем о `@NotNull`, так как первая аннотация допускает null)
Аналогично для даты окончания, но в этом случае следует использовать `@Future`, так как дата окончания должна быть после начала бронирования и не может быть ей равна.

Также над полем `itemId`  можно было бы навесить `@NotNull`, так как при бронировании мы должны передать, какую вещь именно бронируют

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<Map<String, String>> handleException(UnsupportedStateException e) {
Для обработчиков принято заводить отдельный класс, аннотированный `@RestControllerAdvice`
https://struchkov.dev/blog/ru/exception-handling-controlleradvice/

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private static final String userHeaderName = "X-Sharer-User-Id";
Так как поле дублируется во всех классах-контроллерах, хорошо было бы ввести отдельный класс, где будет находиться это поле, чтобы не дублировать его везде)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public List<BookingDto> getBookings(String state, @RequestHeader(userHeaderName) Long userId) {
Можно было бы внутри `@RequestParam(defaultValue = "ALL")` задать стандартное значение, исключив проверку ниже)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public List<BookingDto> getItemsBookings(String state, @RequestHeader(userHeaderName) Long userId) {
Можно было бы внутри `@RequestParam(defaultValue = "ALL")` задать стандартное значение, исключив проверку ниже)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/exception/ValidationException.java
> +@ResponseStatus(
Не потребуется, так как у нас будет отдельный класс с обработчиками, где мы будем обрабатывать исключения, логгировать и возвращать требуемый статус)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +@ResponseStatus(
Не потребуется, так как у нас будет отдельный класс с обработчиками, где мы будем обрабатывать исключения, логгировать и возвращать требуемый статус)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    public CommentDto toDto() {
Аналогично, следует ввести отдельный класс-маппер для методов, связанных с маппингом комментариев)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public ItemDtoWithBooking toDtoWithBookings(Booking current, Booking next, Booking last) {
Аналогично)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public ItemDto toDto() {
Аналогично)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public Item toItem(User user) {
Аналогично)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/CommentInputDto.java
> +public class CommentInputDto {
Хорошо было бы ограничить размеры текстовых полей на основе тех ограничений, которые установлены на уровне таблицы в БД, чтобы заранее откинуть некорректные запросы) Для ограничения количества символов можно использовать `@Size`

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/CommentInputDto.java
> +    private String text;
Также было бы удобно использовать `@NotBlank`, чтобы запретить передачу пустой строки, только из пробелов и `null`

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/CommentInputDto.java
> +    public Comment toComment(Long id, User author, Item item) {
Аналогично, следует вынести в маппер)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
Над полями с названием и описанием можно было бы использовать аннотацию `@NotBlank`, которая пресечет передачу `null` либо же строки только из пробелов)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Boolean available;
Также здесь можно было бы использовать `@NotNull`, чтобы не допустить передачу в качестве этого значения - `null`

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            return new ArrayList<>();
Можно было бы не производить создание нового объекта класса `ArrayList`, а использовать готовую пустую неизменяемую коллекцию `List.of()` или `Collections.emptyList()`

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestBody ItemDto dto, @RequestHeader(userHeaderName) Long userId) {
Здесь также теперь потребуется использовать `@Valid`, чтобы аннотации валидации из класса `ItemDto` стали учитываться)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public CommentDto createComment(@RequestBody CommentInputDto dto, @PathVariable Long itemId, @RequestHeader(userHeaderName) Long userId) {
Здесь также теперь потребуется использовать `@Valid`, чтобы аннотации валидации из класса `CommentInputDto` стали учитываться)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User create(@RequestBody User object) {
Возвращать мы должны не объект класса-сущности, а DTO. Мы всегда должны контролировать те данные, что мы получаем и отдаем, а также именно DTO выступает для представления данных, передаваемых между системами и, например, менять структуру БД, если потребуется изменить содержимое возвращаемых данных, будет не совсем корректно
Аналогично в других местах)

В новом классе `UserDto` можно было бы использовать валидацию по группам)
Для имени:
`@NotBlank(groups = {Create.class})`
Для почты аннотацию `@Email(groups = {Create.class, Update.class})` следует учитываться для обновления и создания, так как, если она не будет передана вообще, то все будет окей, а если будет, тогда она будет проверена на соответствие почте, а вот аннотацию
`@NotEmpty(groups = {Create.class})` только для создания) Так как при обновлении передавать ее не обязательно)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User create(@RequestBody User object) {
Кстати, вместо `@Valid` можно использовать такую аннотацию `@Validated(Create.class)`. Таким образом мы указываем, какую группу аннотаций следует учитывать. `Create` - это интерфейс, который ты создаешь самостоятельно, он будет пустым и служит лишь для указания группы) Аналогично следует поступить при обновлении, но там будет аннотация `@Validated(Update.class)`

Если не использовать валидацию по группам, тогда потребуется при обновлении дополнительно проверять формат переданной строки с почтой в коде, что не очень удобно. Либо же потребуется ввести отдельный класс DTO для обновления, чтобы над полем с почтой использовать `@Email`

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    private void validateUser(User user) {
Валидация теперь будет производиться с помощью аннотаций валидации) Метод более не требуется)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public User change(User original, User user) {
Хорошо было бы также проверить, что строка не пуста и не состоит только из пробелов) Сделать это удобно с помощью метода `isBlank`)
Так как иначе при обновлении допустимо передать такие значения, что при создании - недопустимо)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        if (user.getEmail() == null) {
Хорошо было бы также проверить, что строка не пуста и не состоит только из пробелов) Сделать это удобно с помощью метода `isBlank`)
Так как иначе при обновлении допустимо передать такие значения, что при создании - недопустимо)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    private void validateItem(Item item) {
Более также не потребуется)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        switch (state) {
Для состояний хорошо было бы ввести отдельный Enum, чтобы случайно не ошибиться в названии, а также, в случае, если потребуется его изменить - средствами IDE - сделать это будет в разы легче)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        switch (state) {
Для состояний хорошо было бы ввести отдельный Enum, чтобы случайно не ошибиться в названии, а также, в случае, если потребуется его изменить - средствами IDE - сделать это будет в разы легче)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    private void validateBooking(Booking booking) {
Часть проверок можно будет исключить, так как они будут реализованы с помощью аннотаций валидации)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        } else if (booking.getEnd().isBefore(booking.getStart())) {
(предложение)Эту валидацию можно было бы реализовать с помощью аннотации валидации над классом, чтобы поддерживать декларативный подход https://devcolibri.com/spring-mvc-кастомная-аннотация-для-валидации/
Кстати, если будет интересно то, как реализовать кастомную аннотацию валидации на уровне класса dto - можешь чекнуть тут) https://github.com/TyutterinYakov/CustomValidationClassLevel Я написал небольшой примерчик, чтобы было проще разобраться в теме)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (item.getDescription() == null) {
Хорошо было бы также проверить, что строка не пуста и не состоит только из пробелов) Сделать это удобно с помощью метода `isBlank`)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (item.getName() == null) {
Хорошо было бы также проверить, что строка не пуста и не состоит только из пробелов) Сделать это удобно с помощью метода `isBlank`)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public Item change(Item original, Item item) {
Можно было бы производить изменение не нового объекта класса `Item`, а полученного из БД - `original`, изменяя лишь те поля, что были обновлены, а не перенося все значения в новый) Аналогично при обновлении пользователя

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        for (Item item : items) {
Следует получить комментарии всех вещей, которые будут возвращены вне цикла и разбить их на мапу, где ключ - идентификатор вещи, а значение - коллекция из комментариев) Таким образом мы не будем производить n-лишних запросов к БД) Получение следует произвести вне цикла)
Аналогично следует поступить и с поиском предыдущего и следующего бронирования)
Где можно было бы по коллекции предметов произвести получение и сразу же выполнить сортировку, чтобы поиск небходимых бронирований был проще)
```
		Map<Item, List<Comment>> comments = commentRepository.findByItemIn(items, Sort.by(DESC, "created"))
				.stream()
				.collect(groupingBy(Comment::getItem, toList()));
```
Это лишь предложение по реализации, можно реализовать свою логику, главное избавиться от обращения к методам репозиториев в циклах)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        for (var item : items) {
Фильтрация должна осуществляться с помощью запроса к БД, а не получением всех записей, а затем работа с ними) Записей может быть очень много и на их десериализацию потребуется очень много времени и памяти, что будет не очень эффективно)

2023-08-02 18:57 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    Booking findCurrentBookingByItem(Long itemId);
Методы по работе с сущностью `Booking` должны находиться в репозитории бронирований, так как они являются отдельной сущностью в БД)

2023-08-04 09:21 UTC, DaniilRyndyk1 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
Без сложных объектов тесты не проходятся.

2023-08-04 09:21 UTC, DaniilRyndyk1 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private User booker;
Без сложных объектов тесты не проходятся.

2023-08-04 15:13 UTC, TyutterinYakov approved these changes
Добрый вечер! Поздравляю с успешной сдачей спринта :) Сил и терпения на этом сложном, но интересном пути! Успехов в обучении и прекрасного вечера!🌃🎇

2023-08-04 15:13 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +public class ErrorHandler {
В класс следует добавить логирование) Для этого достаточно использовать аннотацию из lombok ->> `@Slf4j`. Далее в каждый наш хендлер следует добавить логирование сообщения об ошибке)
Также хорошо было бы передать в лог сообщение об ошибке, а можно и весь трейс, чтобы в случае ошибки было проще разобраться, что именно произошло)
Кстати, при логгировании более эффективно использовать не конкатенацию, а заполнитель - placeholder `{}`
Например:
`log.debug("Получен статус 404 Not found {}", ex.getMessage(), ex);`

2023-08-04 15:13 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +//        var items = getAll();
Если код не используется - следует его исключить)

2023-08-04 15:13 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                dto.setComments(comments.get(item).stream().map(commentMapper::toDto).collect(Collectors.toList()));
Выше мы уже получили значение) Повторное обращение к мапе не требуется:
`dto.setComments(commentsByItem.stream().map(commentMapper::toDto).collect(Collectors.toList()));`

2023-08-06 19:48 UTC, merged