Add item requests
DaniilRyndyk1/java-shareit pull request #3
Opened 2023-08-06 19:48 UTC by DaniilRyndyk1

2023-08-09 20:28 UTC, Fleaman777 requested changes

2023-08-09 20:28 UTC, Fleaman777 commented on pom.xml
> +		</dependency>
нужна ли эта зависимость, 
по идеи все необходимое должно быть spring-data-jpa

2023-08-09 20:28 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +            throw new NotFoundException("Пользователь является арендатором");
здесь, и в следующем if else больше подошло бы  ValidationException

2023-08-09 20:28 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        }
этот if можно было бы заменить на тернарный оператор 
var newStatus = approved ? BookingStatus.APPROVED : BookingStatus.REJECTED;
booking.setStatus(newStatus);

2023-08-09 20:28 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        var nexts = bookingRepository.findNextsByUser(userId)
у current, last и next нет множественной формы )

2023-08-09 20:28 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +            result.add(dto);
получился достаточно длинный метод, попробуй его разбить на какие-то логические части, что бы его было проще воспринимать

2023-08-09 20:28 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +public class BookingControllerTests {
по общепринятым правилам, Test - должно быть в единственном числе

2023-08-09 20:28 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +    public ItemRequestDto create(ItemRequestInputDto inputDto, Long userId) {
метод изменяет состояние БД, правильней было бы его выполнять в транзакции, 

относится ко всем аналогичным местам

2023-08-09 20:28 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/dto/BookingInputDtoTest.java
> +    void whenBookingInputDtoEndBeforeNowThenViolationsShouldBeReportedNotNull() {
хорошее навзание тест метода, содержит инфу о том, что тестирует и какой ожидается результат

2023-08-09 20:28 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/handler/ErrorHandlerTests.java
> +    }
в целом, можно не тестировать хэндлер, если только в нем не содержится какая-нибудь кастомная логика

2023-08-09 20:28 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/user/dto/UserDtoTest.java
> +}
отличные тесты, покрывают достаточно много кейсов, 
но еще нужно дописать немного другого типа 

необходимо еще написать тесты для репозиторий слоев,
в задании написано, покрыть тестами кастомные методы, по сути, все методы которые находятся в ....Repository являются кастомными,
некастомные методы, это методы в интерфейсе JpaRepository (save, find..) их соответственно тестировать не нужно

и еще написать интеграционные тесты не на все методы сервисов, а только на 1 основной(см задание), 
те тесты которые у тебя написаны на сервисы больше похоже на юнит тесты

2023-08-09 21:06 UTC, DaniilRyndyk1 commented on pom.xml
> +		</dependency>
Удалил, действительно не нужна

2023-08-09 21:07 UTC, DaniilRyndyk1 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +            throw new NotFoundException("Пользователь является арендатором");
Я изначально ставил ValidationException, но Postman тесты хотят ответ как от NotFoundException (как и во всех аналогичных местах), код ошибки и текст от Validation не подходят

2023-08-09 21:08 UTC, DaniilRyndyk1 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        }
Изначально использовал тернарный оператор, но с ним некорректно считается покрытие branch тестами почему-то, после разделения на обычный if все заработало

2023-08-09 21:09 UTC, DaniilRyndyk1 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        var nexts = bookingRepository.findNextsByUser(userId)
Поправил

2023-08-09 21:10 UTC, DaniilRyndyk1 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +public class BookingControllerTests {
Поправил

2023-08-09 21:11 UTC, DaniilRyndyk1 commented on src/test/java/ru/practicum/shareit/handler/ErrorHandlerTests.java
> +    }
Я планировал не писать тест для хэндера, но в гит тестах есть обязательное покрытие всех классов моими тестами, просто не пропускало, пришлось добавить

2023-08-09 21:12 UTC, DaniilRyndyk1 commented on src/test/java/ru/practicum/shareit/user/dto/UserDtoTest.java
> +}
Для репозиториев добавлю, в сервисах изначально немного тестов было, но гит тесты требуют покрытия 90% всех строк, пришлось доскональные тесты писать

2023-08-09 21:18 UTC, DaniilRyndyk1 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +            result.add(dto);
Поправил, вынес повторяющийся код в функцию + небольшой рефакторинг

2023-08-09 23:41 UTC, DaniilRyndyk1 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +    public ItemRequestDto create(ItemRequestInputDto inputDto, Long userId) {
Поправил, во всех сервисах добавил транзакции, соответственно сократил код

2023-08-10 01:12 UTC, DaniilRyndyk1 commented on src/test/java/ru/practicum/shareit/user/dto/UserDtoTest.java
> +}
Добавил тесты для репозиториев. Примите, пожалуйста, в текущей итерации, впритык времени остается на последнее ТЗ

2023-08-10 18:30 UTC, Fleaman777 approved these changes

2023-08-11 19:26 UTC, merged